server:
  port: 8080
#springfox:
#  documentation:
#    swagger-ui:
#      enabled: true
spring:
  datasource:
    url: jdbc:mysql://kh-dev-mysql-application.cy77l4kz6vr9.ap-south-1.rds.amazonaws.com/dev_demo_interview?zeroDateTimeBehavior=convertToNull&createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
      #    username: ${SPRING_DATASOURCE_USERNAME:root}
    username: bharatgupta
      #    password: ${SPRING_DATASOURCE_USERNAME:root}
    password: ZGU0NGJmZjhl

  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 1000